# Site settings
title: ENTREC CLUB
email: msf@syahmifauzi.com
description: > # Multiline description..
  Site description goes here..

# Uncomment 'baseurl' and 'url' when deploy..
baseurl: "/entrec"
url: "http://www.syahmifauzi.com"

twitter_username: twitter.entrec
facebook_username:  entrec.iium
instagram_username: entrec.club

# Build settings..
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/ # just pretty
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md", "bower.json", ".bowerrc", "bower_components"]
